config/routes.rb
Rails.application.routes.draw do

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index" #or get '/' => "welcome#index" #go to homepage
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  get "/admin/listings" => "admins#unverified_listings", as: "admin_listings"

  post "/listing/:id/verify" => "listings#verify", as: "verify"

  resources :listings 



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  def self.create_with_omniauth(auth_hash)
    self.new(
      provider: auth_hash["provider"],
      uid: auth_hash["uid"]
      # token: auth_hash["credentials"]["token"]
    )
  end

  # def update_token(auth_hash)
  #   self.token = auth_hash["credentials"]["token"]
  #   self.save
  # end
end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
 include Clearance::User
 has_many :authentications, dependent: :destroy
 has_many :listings
 enum role: ["customer", "host", "moderator", "admin"]

 def self.create_with_auth_and_hash(authentication, auth_hash)
   user = self.create!(
     name: auth_hash["info"]["name"],
     email: auth_hash["info"]["email"],
     password: SecureRandom.hex(10)
   )
   user.authentications << authentication
   return user
 end

 # # grab google to access google for user data
 # def google_token
 #   x = self.authentications.find_by(provider: 'google_oauth2')
 #   return x.token unless x.nil?
 # end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :require_moderator

	def unverified_listings
		@listings = Listing.where(verified: false)
		render "listings_index" # without this line it would have gone to unverified_listings.html.erb
	end

	private
	def require_moderator
		unless current_user.moderator? || current_user.admin?
			redirect_to listings_path
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	before_action :require_host, only: [:new, :create]
	before_action :require_owner, only: [:edit, :update, :destroy]
	before_action :require_moderator, only: :verify
	before_action :set_listing, only: [:edit, :update, :destroy, :verify]

	def index
		@listings = Listing.where(verified: true)
	end

	def new
		@listing = Listing.new
	end

	def create
		@listing = current_user.listings.new(listing_params)
		@listing.save
		redirect_to listing_path(@listing) #listing/:id
	end

	def show
		# @listing = Listing.find(params[:id])
	end

	def edit
		# @listing = Listing.find(params[:id])
	end

	def update
		# @listing = Listing.find(params[:id])
		@listing.update(listing_params)
		redirect_to listing_path(@listing)
	end

	def destroy
		# @listing = Listing.find(params[:id])
		@listing.destroy
		redirect_to listings_path
	end

	def verify
		# @listing = Listing.find(params[:id])
		@listing.update(verified: true)
		redirect_to admin_listings_path
	end

	private
	def listing_params
		params.require(:listing).permit(:location,:tags,:name,:place_type, :property_type, :room_number, :bed_number, :guest_number,:country,:state, :city, :zipcode, :price, :description)
	end

	def require_host
		unless current_user.host? || current_user.admin?
			redirect_to listings_path
		end
	end

	def require_owner
		set_listing
		unless current_user == listing.user || current_user.admin?
			redirect_to listings_path
		end
	end

	def require_moderator
		unless current_user.moderator? || current_user.admin?
			redirect_to listings_path
		end
	end

	def set_listing
		@listing = Listing.find(params[:id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController

def create_from_omniauth
  auth_hash = request.env["omniauth.auth"] #save google account's data into this variable
  authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) ||  Authentication.create_with_omniauth(auth_hash)

  # if: previously already logged in with OAuth
  if authentication.user
    user = authentication.user
    # authentication.update_token(auth_hash)
    # @next = root_url #or root_path
    @notice = "Signed in!"
  # else: user logs in with OAuth for the first time
  else
    user = User.create_with_auth_and_hash(authentication, auth_hash)
    # you are expected to have a path that leads to a page for editing user details
    # @next = edit_user_path(user) #edit account
    @notice = "User created. Please confirm or edit details"
  end

  sign_in(user)
  redirect_to listings_path, :notice => @notice 
  #flash calls notice in views by flash[:notice] or loop notice by <% flash.each do |key, value| %><div class="flash <%= key %>"><%= value %></div>
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
	
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/listings_index.html.erb
<% @listings.each do |t| %>
	<%= t.name %>
	<%= t.location %>
	RM <%= t.price %>
	<%= button_to "Verify", verify_path(t) %>
<% end %>

<%= link_to "Listing", new_listing_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PAIRBNB20</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= button_to 'Sign out', sign_out_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <%= link_to "Sign in with Google", "/auth/google_oauth2" %>
    <% end %>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/listings/edit.html.erb
<%= form_for @listing do |x| %>
	Location: <%= x.text_field :location, placeholder: "Location" %></br>
    Tags <%= x.text_field :tags %></br>
    Name <%= x.text_field :name %></br>
    Place Type<%= x.number_field :place_type %></br>
   	Property Type<%= x.text_field :property_type %></br>
    Room Number<%= x.number_field :room_number %></br>
    Bed Number<%= x.number_field :bed_number %></br>
    <%= x.number_field :guest_number %></br>
   	<%= x.text_field :country %></br>
   	<%= x.text_field :state %></br>
   	<%= x.text_field :city %></br>
    <%= x.number_field :zipcode %></br>
    <%= x.number_field :price %></br>
   	<%= x.text_field :description %></br>
   	<%= x.submit %>
<% end %>

app/views/listings/index.html.erb
<% @listings.each do |t| %>
	<%= t.name %>
	<%= t.location %>
	RM <%= t.price %>
<% end %>

<% if current_user.admin? || current_user.host? %>
	<%= link_to "Create new listing", new_listing_path %>
<% end %>
<% if current_user.admin? || current_user.moderator? %>
	<%= link_to "Unverified Listings", admin_listings_path %>
<% end %>

app/views/listings/new.html.erb
<%= form_for @listing do |x| %>
	Location: <%= x.text_field :location, placeholder: "Location" %></br>
    Tags <%= x.text_field :tags %></br>
    Name <%= x.text_field :name %></br>
    Place Type<%= x.number_field :place_type %></br>
   	Property Type<%= x.text_field :property_type %></br>
    Room Number<%= x.number_field :room_number %></br>
    Bed Number<%= x.number_field :bed_number %></br>
    <%= x.number_field :guest_number %></br>
   	<%= x.text_field :country %></br>
   	<%= x.text_field :state %></br>
   	<%= x.text_field :city %></br>
    <%= x.number_field :zipcode %></br>
    <%= x.number_field :price %></br>
   	<%= x.text_field :description %></br>
   	<%= x.submit %>
<% end %>

app/views/listings/show.html.erb
<%= @listing.name %>
<%= @listing.location %>
RM <%= @listing.price %>

<%= link_to "Edit", edit_listing_path(@listing) %>
<%= button_to "Delete", listing_path(@listing), method: :delete, data: {confirm: "u sure?"} %>

app/views/welcome/index.html.erb
Welcome to PAIRBNB!